version: '3.7'

services:

  postgres:
    image: postgres:11
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: taxi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
    ports:
      - 5432:5432
    volumes:
      - ./../data/postgres/data:/var/lib/postgresql/data
    networks:
      - pg-network


networks:
  pg-network:
    name: pg-network
    driver: bridge
